version: '3'
services:
  mysql:
    image: mysql:8.3
    restart: unless-stopped
    container_name: neo-finance-db
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - "3307:3306"
    volumes:
      - .data/db:/var/lib/mysql